select database();
select * from CREDIT_CARD_CUSTOMERS limit 10;
select count(*) from CREDIT_CARD_CUSTOMERS;
select distinct ATTRITION_FLAG from CREDIT_CARD_CUSTOMERS;
select CLIENTNUM, count(*) FROM CREDIT_CARD_CUSTOMERS group by CLIENTNUM having count(*) > 1;
select
count(*) - count(CUSTOMER_AGE) AS MISSING_AGE,
count(*) - count(INCOME_CATEGORY) AS MISSING_INCOME,
count(*) - count(GENDER) AS MISSING_GENDER
from CREDIT_CARD_CUSTOMERS;
select distinct EDUCATION_LEVEL from CREDIT_CARD_CUSTOMERS;
select distinct MARITAL_STATUS from CREDIT_CARD_CUSTOMERS;
select distinct INCOME_CATEGORY from CREDIT_CARD_CUSTOMERS;
select
count(*) as TOTAL_CUSTOMERS,
sum(CASE when ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0
END) AS CHURNED_CUSTOMERS,
ROUND(100 * SUM(CASE 
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0
END) / COUNT(*), 2) AS CHURN_RATE_PCT FROM CREDIT_CARD_CUSTOMERS;
SELECT
CARD_CATEGORY, 
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(100 * SUM(CASE WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) / COUNT(*), 2) AS CHURN_RATE
FROM CREDIT_CARD_CUSTOMERS
GROUP BY CARD_CATEGORY
ORDER BY CHURN_RATE DESC;
SELECT
CASE 
WHEN CUSTOMER_AGE < 30 THEN 'BELOW 30'
WHEN CUSTOMER_AGE BETWEEN 30 AND 39 THEN '30-39'
WHEN CUSTOMER_AGE BETWEEN 40 AND 49 THEN '40-49'
WHEN CUSTOMER_AGE BETWEEN 50 AND 59 THEN '50-59'
ELSE '60+'
END AS AGE_GROUP,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE 
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(100 * SUM(CASE
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) / COUNT(*), 2) AS CHURN_RATE
FROM CREDIT_CARD_CUSTOMERS
GROUP BY AGE_GROUP
ORDER BY CHURN_RATE DESC;
SELECT 
MONTHS_INACTIVE_12_MON,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(100 * SUM(CASE 
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) / COUNT(*), 2) AS CHURN_RATE
FROM CREDIT_CARD_CUSTOMERS
GROUP BY MONTHS_INACTIVE_12_MON
ORDER BY CHURN_RATE DESC;
SELECT 
CASE 
WHEN TOTAL_TRANS_CT < 30 THEN 'LOW USAGE'
WHEN TOTAL_TRANS_CT BETWEEN 30 AND 70 THEN 'MEDIUM USAGE'
ELSE 'HIGH USAGE'
END AS USAGE_SEGMENT,
COUNT(*) AS TOTAL_CUSTOMERS,
SUM(CASE
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) AS CHURNED_CUSTOMERS,
ROUND(100 * SUM(CASE
WHEN ATTRITION_FLAG = 'ATTRITED CUSTOMER' THEN 1
ELSE 0 END) / COUNT(*), 2) AS CHURN_RATE
FROM CREDIT_CARD_CUSTOMERS
GROUP BY USAGE_SEGMENT
ORDER BY CHURN_RATE DESC;